### ISSUE TITLE
agent模块的Push函数内缺少continue语句

### ISSUE THREAD

**Issue by zhangnian** [URLooker/agent#1]
Line：24
if len(itemResults) == 0 {
      time.Sleep(1 \* time.Second)
}
应该为：
if len(itemResults) == 0 {
    time.Sleep(1 \* time.Second)
    continue
}
没有continue则会继续执行，从而发送一个不包含任何查询结果的消息到Web模块

**Comment by 710leo** [comment]
@zhangnian 感谢反馈问题，已修改 : )
